language: android
sudo: required

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository

install:
  - yes | sdkmanager "ndk-bundle"

before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

script:
  - bash ./gradlew assembleRelease --no-daemon
