name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt-hotspot
        java-version: 11
        cache: gradle
    - name: Build
      run: bash ./gradlew assembleEmbedNoRecordRelease assembleEmbedNoRecordDebug bundleEmbedNoRecordRelease
    - name: Artifact (Debug APK)
      uses: actions/upload-artifact@v2
      with:
        name: ls2.apk
        path: app/build/outputs/apk/embedNoRecord/debug/app-embed-noRecord-debug.apk
    - name: Artifact (Unsigned APK)
      uses: actions/upload-artifact@v2
      with:
        name: ls2-unsigned.apk
        path: app/build/outputs/apk/embedNoRecord/release/app-embed-noRecord-release-unsigned.apk
    - name: Artifact (AAB)
      uses: actions/upload-artifact@v2
      with:
        name: ls2.aab
        path: app/build/outputs/bundle/embedRecordRelease/app-embed-noRecord-release.aab
