name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt-hotspot
        java-version: 17
        cache: gradle
    - name: Build
      run: bash ./gradlew assembleEmbedNoRecordRelease assembleEmbedNoRecordDebug bundleEmbedNoRecordRelease
    - name: Artifact (Debug APK)
      uses: actions/upload-artifact@v3
      with:
        name: love-android-debug.apk
        path: app/build/outputs/apk/embedNoRecord/debug/app-embed-noRecord-debug.apk
    - name: Artifact (Release APK)
      uses: actions/upload-artifact@v2
      with:
        name: love-android.apk
        path: app/build/outputs/apk/embedNoRecord/release/app-embed-noRecord-release-unsigned.apk
    - name: Artifact (Embed AAB)
      uses: actions/upload-artifact@v3
      with:
        name: love-android-embed.aab
        path: app/build/outputs/bundle/embedNoRecordRelease/app-embed-noRecord-release.aab
